#!/bin/bash
#PBS -l walltime=240:00:00
#PBS -l nodes=1:ppn=48:huskey,mem=480gb
#PBS -N ccs_lab_mriqc_trimmed_flow_dynamic
#PBS -j oe
#PBS -m abe -M huskey.29@osu.edu

#COMMANDS TO RUN
module load singularity
singularity run --cleanenv /fs/project/huskey.29/flow_dynamic/singularity_images/poldracklab_mriqc_0.14.2-2018-08-21-0f8229583796.img /fs/project/huskey.29/flow_dynamic/bids_nii_trimmed/merged/ /fs/project/huskey.29/flow_dynamic/mriqc_trimmed_output/ participant -w /fs/project/huskey.29/flow_dynamic/mriqc_trimmed_work/ --n_procs 48
